allowBuilds:
  esbuild: false

catalogMode: strict

packages:
  - 11ty/**
  - slidev/**

catalogs:
  11ty:
    "@11ty/eleventy": 3.1.5
    budoux: 0.8.4
    markdown-it: 14.2.0
    markdown-it-footnote: 4.0.0
  root:
    gh-pages: 6.3.0
  slidev:
    "@slidev/cli": 52.15.2
    "@slidev/theme-default": 0.25.0
    '@slidev/theme-apple-basic': 0.25.1
    "@iconify-json/vscode-icons": 1.2.51
    vue: 3.5.35
